CREATE TABLE ServiceTypes (
  ServiceTypeID INTEGER GENERATED AS IDENTITY PRIMARY KEY,
  Name VARCHAR2(50) NOT NULL
);

CREATE TABLE Appointments (
  AppointmentID INTEGER PRIMARY KEY GENERATED AS IDENTITY (START WITH 1 NOCYCLE NOORDER),
  Clients INTEGER NOT NULL,
  Provided2 INTEGER,
  Provided3 INTEGER,
  Date DATE NOT NULL,
  Time TIMESTAMP NOT NULL,
  PaymentType VARCHAR2(30),
  Status VARCHAR2(30) NOT NULL
);

CREATE TABLE Clients (
  ClientID INTEGER PRIMARY KEY GENERATED AS IDENTITY (START WITH 1 NOCYCLE NOORDER),
  DiscountTypes INTEGER,
  FirstName VARCHAR2(25) NOT NULL,
  LastName VARCHAR2(25) NOT NULL,
  MiddleName VARCHAR2(25),
  PhoneNumber INTEGER NOT NULL,
  Email VARCHAR2(25)
);

CREATE TABLE Create (
  Employees INTEGER NOT NULL,
  Appointments INTEGER NOT NULL,
  PRIMARY KEY (Employees, Appointments)
);

CREATE TABLE DiscountTypes (
  DiscountTypeID INTEGER PRIMARY KEY GENERATED AS IDENTITY (START WITH 1 NOCYCLE NOORDER),
  Description VARCHAR2(50) NOT NULL,
  Percentage FLOAT NOT NULL,
  CHECK (Percentage BETWEEN 0 AND 1)
);

CREATE TABLE Employees (
  EmployeeID INTEGER PRIMARY KEY GENERATED AS IDENTITY (START WITH 1 NOCYCLE NOORDER),
  Salons INTEGER NOT NULL,
  FirstName VARCHAR2(25) NOT NULL,
  LastName VARCHAR2(25) NOT NULL,
  MiddleName VARCHAR2(25),
  DateOfBirth DATE NOT NULL,
  Schedule VARCHAR2(25),
  CHECK (DateOfBirth < CURRENT_DATE)
);

CREATE TABLE Materials (
  MaterialID INTEGER PRIMARY KEY GENERATED AS IDENTITY (START WITH 1 NOCYCLE NOORDER),
  Units INTEGER NOT NULL,
  Name VARCHAR2(25) NOT NULL
);

CREATE TABLE Members (
  Supplies INTEGER NOT NULL,
  Materials INTEGER NOT NULL,
  Expiration DATE NOT NULL,
  Count INTEGER NOT NULL,
  Cost NUMBER(8,2) NOT NULL,
  CHECK (Count >= 0),
  CHECK (Cost >= 1),
  PRIMARY KEY (Supplies, Materials)
);

CREATE TABLE Owners (
  OwnerID INTEGER PRIMARY KEY GENERATED AS IDENTITY (START WITH 1 NOCYCLE NOORDER),
  FirstName VARCHAR2(25) NOT NULL,
  LastName VARCHAR2(25) NOT NULL,
  MiddleName VARCHAR2(25),
  PhoneNumber INTEGER NOT NULL
);

CREATE TABLE Promotions (
  PromotionID INTEGER PRIMARY KEY GENERATED AS IDENTITY (START WITH 1 NOCYCLE NOORDER),
  Name VARCHAR2(25) NOT NULL,
  StartDate DATE NOT NULL,
  EndDate DATE NOT NULL,
  Description VARCHAR2(100) NOT NULL,
  Percent FLOAT,
  CHECK (Percent IS NULL OR (Percent BETWEEN 0 AND 1)),
  CHECK (EndDate >= StartDate)
);

CREATE TABLE Provided2 (
  Services INTEGER NOT NULL,
  Employees INTEGER NOT NULL,
  Cost NUMBER(8,2) NOT NULL,
  PRIMARY KEY (Services, Employees)
);

CREATE TABLE Salons (
  SalonID INTEGER PRIMARY KEY GENERATED AS IDENTITY (START WITH 1 NOCYCLE NOORDER),
  Owners INTEGER NOT NULL,
  Name VARCHAR2(25) NOT NULL,
  Address VARCHAR2(70) NOT NULL
);

CREATE TABLE Services (
  ServiceID INTEGER PRIMARY KEY GENERATED AS IDENTITY (START WITH 1 NOCYCLE NOORDER),
  Name VARCHAR2(25) NOT NULL,
  ServiceTypeID INTEGER,
  CONSTRAINT FK_ServiceType FOREIGN KEY (ServiceTypeID) REFERENCES ServiceTypes(ServiceTypeID)
);

CREATE TABLE Suppliers (
  SupplierID INTEGER PRIMARY KEY GENERATED AS IDENTITY (START WITH 1 NOCYCLE NOORDER),
  Name VARCHAR2(50) NOT NULL,
  PhoneNumber INTEGER NOT NULL
);

CREATE TABLE Supplies (
  SupplyID INTEGER PRIMARY KEY GENERATED AS IDENTITY (START WITH 1 NOCYCLE NOORDER),
  Salons INTEGER NOT NULL,
  Suppliers INTEGER NOT NULL,
  SupplyDate DATE NOT NULL
);

CREATE TABLE Units (
  UnitID INTEGER PRIMARY KEY GENERATED AS IDENTITY (START WITH 1 NOCYCLE NOORDER),
  Denomination VARCHAR2(10) NOT NULL
);

CREATE TABLE Uses (
  Materials INTEGER NOT NULL,
  Services INTEGER NOT NULL,
  PRIMARY KEY (Materials, Services)
);

CREATE TABLE Works1 (
  Services INTEGER NOT NULL,
  Promotions INTEGER NOT NULL,
  PRIMARY KEY (Services, Promotions)
);
